
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jun 12 2024 13:56:50 IST (Jun 12 2024 08:26:50 UTC)

// Verification Directory fv/vedic4bit 

module andg(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X2 g10__2398(.A (a), .B (b), .Y (y));
endmodule

module andg_30(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__5107(.A (a), .B (b), .Y (y));
endmodule

module andg_29(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__6260(.A (a), .B (b), .Y (y));
endmodule

module hag(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  AOI2BB1X2 g24__4319(.A0N (a), .A1N (b), .B0 (c), .Y (s));
  AND2X1 g25__8428(.A (b), .B (a), .Y (c));
endmodule

module andg_28(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__5526(.A (a), .B (b), .Y (y));
endmodule

module andg_27(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__6783(.A (a), .B (b), .Y (y));
endmodule

module andg_26(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__3680(.A (a), .B (b), .Y (y));
endmodule

module fag(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g66__1617(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_40(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  AOI2BB1X2 g24__2802(.A0N (b), .A1N (a), .B0 (c), .Y (s));
  AND2X1 g25__1705(.A (b), .B (a), .Y (c));
endmodule

module andg_25(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__5122(.A (a), .B (b), .Y (y));
endmodule

module andg_24(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__8246(.A (a), .B (b), .Y (y));
endmodule

module andg_23(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__7098(.A (a), .B (b), .Y (y));
endmodule

module fag_37(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g66__6131(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module andg_22(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__1881(.A (a), .B (b), .Y (y));
endmodule

module hag_39(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__5115(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_36(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g66__7482(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_21(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__4733(.A (a), .B (b), .Y (y));
endmodule

module andg_20(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__6161(.A (a), .B (b), .Y (y));
endmodule

module andg_19(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__9315(.A (a), .B (b), .Y (y));
endmodule

module fag_35(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g66__9945(.A (b), .B (a), .CI (cin), .S (s), .CO (c));
endmodule

module hag_38(s, c, a, b);
  input a, b;
  output s, c;
  wire a, b;
  wire s, c;
  ADDHXL g24__2883(.A (b), .B (a), .S (s), .CO (c));
endmodule

module fag_34(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g66__2346(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_18(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__1666(.A (a), .B (b), .Y (y));
endmodule

module andg_17(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__7410(.A (a), .B (b), .Y (y));
endmodule

module fag_33(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g66__6417(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module fag_32(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g66__5477(.A (cin), .B (b), .CI (a), .S (s), .CO (c));
endmodule

module andg_16(y, a, b);
  input a, b;
  output y;
  wire a, b;
  wire y;
  AND2X1 g10__2398(.A (a), .B (b), .Y (y));
endmodule

module fag_31(s, c, a, b, cin);
  input a, b, cin;
  output s, c;
  wire a, b, cin;
  wire s, c;
  ADDFX2 g66__5107(.A (b), .B (cin), .CI (a), .S (s), .CO (c));
endmodule

module vedic4bit(p, a, b);
  input [3:0] a, b;
  output [7:0] p;
  wire [3:0] a, b;
  wire [7:0] p;
  wire [32:1] w;
  andg z1(p[0], a[0], b[0]);
  andg_30 z2(w[1], a[1], b[0]);
  andg_29 z3(w[2], a[0], b[1]);
  hag z4(p[1], w[3], w[1], w[2]);
  andg_28 z5(w[4], a[2], b[0]);
  andg_27 z6(w[5], a[1], b[1]);
  andg_26 z7(w[6], a[0], b[2]);
  fag z8(w[7], w[8], w[4], w[5], w[6]);
  hag_40 z9(p[2], w[9], w[3], w[7]);
  andg_25 z10(w[10], a[3], b[0]);
  andg_24 z11(w[11], a[2], b[1]);
  andg_23 z12(w[12], a[1], b[2]);
  fag_37 z13(w[13], w[14], w[10], w[11], w[12]);
  andg_22 z14(w[15], a[0], b[3]);
  hag_39 z15(w[16], w[17], w[13], w[15]);
  fag_36 z16(p[3], w[18], w[16], w[8], w[9]);
  andg_21 z17(w[19], a[3], b[1]);
  andg_20 z19(w[20], a[2], b[2]);
  andg_19 z20(w[21], a[1], b[3]);
  fag_35 z21(w[22], w[23], w[20], w[21], w[19]);
  hag_38 z22(w[24], w[25], w[22], w[14]);
  fag_34 z23(p[4], w[26], w[18], w[17], w[24]);
  andg_18 z24(w[27], a[2], b[3]);
  andg_17 z25(w[28], a[3], b[2]);
  fag_33 z26(w[29], w[30], w[23], w[27], w[28]);
  fag_32 z27(p[5], w[31], w[26], w[25], w[29]);
  andg_16 z28(w[32], a[3], b[3]);
  fag_31 z29(p[6], p[7], w[31], w[30], w[32]);
endmodule

